// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: satact_trace.proto

#include "satact_trace.pb.h"
#include "satact_trace.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace satact_trace {

static const char* SATActTraceServer_method_names[] = {
  "/satact_trace.SATActTraceServer/query_branch",
};

std::unique_ptr< SATActTraceServer::Stub> SATActTraceServer::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< SATActTraceServer::Stub> stub(new SATActTraceServer::Stub(channel, options));
  return stub;
}

SATActTraceServer::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_query_branch_(SATActTraceServer_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status SATActTraceServer::Stub::query_branch(::grpc::ClientContext* context, const ::satact_trace::BranchRequest& request, ::satact_trace::BranchDecision* response) {
  return ::grpc::internal::BlockingUnaryCall< ::satact_trace::BranchRequest, ::satact_trace::BranchDecision, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_query_branch_, context, request, response);
}

void SATActTraceServer::Stub::async::query_branch(::grpc::ClientContext* context, const ::satact_trace::BranchRequest* request, ::satact_trace::BranchDecision* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::satact_trace::BranchRequest, ::satact_trace::BranchDecision, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_query_branch_, context, request, response, std::move(f));
}

void SATActTraceServer::Stub::async::query_branch(::grpc::ClientContext* context, const ::satact_trace::BranchRequest* request, ::satact_trace::BranchDecision* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_query_branch_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::satact_trace::BranchDecision>* SATActTraceServer::Stub::PrepareAsyncquery_branchRaw(::grpc::ClientContext* context, const ::satact_trace::BranchRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::satact_trace::BranchDecision, ::satact_trace::BranchRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_query_branch_, context, request);
}

::grpc::ClientAsyncResponseReader< ::satact_trace::BranchDecision>* SATActTraceServer::Stub::Asyncquery_branchRaw(::grpc::ClientContext* context, const ::satact_trace::BranchRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncquery_branchRaw(context, request, cq);
  result->StartCall();
  return result;
}

SATActTraceServer::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SATActTraceServer_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SATActTraceServer::Service, ::satact_trace::BranchRequest, ::satact_trace::BranchDecision, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](SATActTraceServer::Service* service,
             ::grpc::ServerContext* ctx,
             const ::satact_trace::BranchRequest* req,
             ::satact_trace::BranchDecision* resp) {
               return service->query_branch(ctx, req, resp);
             }, this)));
}

SATActTraceServer::Service::~Service() {
}

::grpc::Status SATActTraceServer::Service::query_branch(::grpc::ServerContext* context, const ::satact_trace::BranchRequest* request, ::satact_trace::BranchDecision* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace satact_trace
#include <grpcpp/ports_undef.inc>

