// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: satact_trace.proto
#ifndef GRPC_satact_5ftrace_2eproto__INCLUDED
#define GRPC_satact_5ftrace_2eproto__INCLUDED

#include "satact_trace.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace satact_trace {

class SATActTraceServer final {
 public:
  static constexpr char const* service_full_name() {
    return "satact_trace.SATActTraceServer";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status query_branch(::grpc::ClientContext* context, const ::satact_trace::BranchRequest& request, ::satact_trace::BranchDecision* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::satact_trace::BranchDecision>> Asyncquery_branch(::grpc::ClientContext* context, const ::satact_trace::BranchRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::satact_trace::BranchDecision>>(Asyncquery_branchRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::satact_trace::BranchDecision>> PrepareAsyncquery_branch(::grpc::ClientContext* context, const ::satact_trace::BranchRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::satact_trace::BranchDecision>>(PrepareAsyncquery_branchRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void query_branch(::grpc::ClientContext* context, const ::satact_trace::BranchRequest* request, ::satact_trace::BranchDecision* response, std::function<void(::grpc::Status)>) = 0;
      virtual void query_branch(::grpc::ClientContext* context, const ::satact_trace::BranchRequest* request, ::satact_trace::BranchDecision* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::satact_trace::BranchDecision>* Asyncquery_branchRaw(::grpc::ClientContext* context, const ::satact_trace::BranchRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::satact_trace::BranchDecision>* PrepareAsyncquery_branchRaw(::grpc::ClientContext* context, const ::satact_trace::BranchRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status query_branch(::grpc::ClientContext* context, const ::satact_trace::BranchRequest& request, ::satact_trace::BranchDecision* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::satact_trace::BranchDecision>> Asyncquery_branch(::grpc::ClientContext* context, const ::satact_trace::BranchRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::satact_trace::BranchDecision>>(Asyncquery_branchRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::satact_trace::BranchDecision>> PrepareAsyncquery_branch(::grpc::ClientContext* context, const ::satact_trace::BranchRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::satact_trace::BranchDecision>>(PrepareAsyncquery_branchRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void query_branch(::grpc::ClientContext* context, const ::satact_trace::BranchRequest* request, ::satact_trace::BranchDecision* response, std::function<void(::grpc::Status)>) override;
      void query_branch(::grpc::ClientContext* context, const ::satact_trace::BranchRequest* request, ::satact_trace::BranchDecision* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::satact_trace::BranchDecision>* Asyncquery_branchRaw(::grpc::ClientContext* context, const ::satact_trace::BranchRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::satact_trace::BranchDecision>* PrepareAsyncquery_branchRaw(::grpc::ClientContext* context, const ::satact_trace::BranchRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_query_branch_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status query_branch(::grpc::ServerContext* context, const ::satact_trace::BranchRequest* request, ::satact_trace::BranchDecision* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_query_branch : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_query_branch() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_query_branch() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status query_branch(::grpc::ServerContext* /*context*/, const ::satact_trace::BranchRequest* /*request*/, ::satact_trace::BranchDecision* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestquery_branch(::grpc::ServerContext* context, ::satact_trace::BranchRequest* request, ::grpc::ServerAsyncResponseWriter< ::satact_trace::BranchDecision>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_query_branch<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_query_branch : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_query_branch() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::satact_trace::BranchRequest, ::satact_trace::BranchDecision>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::satact_trace::BranchRequest* request, ::satact_trace::BranchDecision* response) { return this->query_branch(context, request, response); }));}
    void SetMessageAllocatorFor_query_branch(
        ::grpc::MessageAllocator< ::satact_trace::BranchRequest, ::satact_trace::BranchDecision>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::satact_trace::BranchRequest, ::satact_trace::BranchDecision>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_query_branch() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status query_branch(::grpc::ServerContext* /*context*/, const ::satact_trace::BranchRequest* /*request*/, ::satact_trace::BranchDecision* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* query_branch(
      ::grpc::CallbackServerContext* /*context*/, const ::satact_trace::BranchRequest* /*request*/, ::satact_trace::BranchDecision* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_query_branch<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_query_branch : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_query_branch() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_query_branch() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status query_branch(::grpc::ServerContext* /*context*/, const ::satact_trace::BranchRequest* /*request*/, ::satact_trace::BranchDecision* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_query_branch : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_query_branch() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_query_branch() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status query_branch(::grpc::ServerContext* /*context*/, const ::satact_trace::BranchRequest* /*request*/, ::satact_trace::BranchDecision* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestquery_branch(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_query_branch : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_query_branch() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->query_branch(context, request, response); }));
    }
    ~WithRawCallbackMethod_query_branch() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status query_branch(::grpc::ServerContext* /*context*/, const ::satact_trace::BranchRequest* /*request*/, ::satact_trace::BranchDecision* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* query_branch(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_query_branch : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_query_branch() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::satact_trace::BranchRequest, ::satact_trace::BranchDecision>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::satact_trace::BranchRequest, ::satact_trace::BranchDecision>* streamer) {
                       return this->Streamedquery_branch(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_query_branch() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status query_branch(::grpc::ServerContext* /*context*/, const ::satact_trace::BranchRequest* /*request*/, ::satact_trace::BranchDecision* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedquery_branch(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::satact_trace::BranchRequest,::satact_trace::BranchDecision>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_query_branch<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_query_branch<Service > StreamedService;
};

}  // namespace satact_trace


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_satact_5ftrace_2eproto__INCLUDED
