// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: satact_trace.proto
// Protobuf C++ Version: 6.31.1

#ifndef satact_5ftrace_2eproto_2epb_2eh
#define satact_5ftrace_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6031001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_satact_5ftrace_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_satact_5ftrace_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_satact_5ftrace_2eproto;
}  // extern "C"
namespace satact_trace {
enum Action : int;
extern const uint32_t Action_internal_data_[];
enum ResponsePayload : int;
extern const uint32_t ResponsePayload_internal_data_[];
class BranchDecision;
struct BranchDecisionDefaultTypeInternal;
extern BranchDecisionDefaultTypeInternal _BranchDecision_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull BranchDecision_class_data_;
class BranchRequest;
struct BranchRequestDefaultTypeInternal;
extern BranchRequestDefaultTypeInternal _BranchRequest_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull BranchRequest_class_data_;
}  // namespace satact_trace
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::satact_trace::Action_internal_data_>
    internal::EnumTraitsImpl::value<::satact_trace::Action>;
template <>
internal::EnumTraitsT<::satact_trace::ResponsePayload_internal_data_>
    internal::EnumTraitsImpl::value<::satact_trace::ResponsePayload>;
}  // namespace protobuf
}  // namespace google

namespace satact_trace {
enum ResponsePayload : int {
  RESPONSE_PAYLOAD_UNSPECIFIED = 0,
  RESPONSE_PAYLOAD_COMPACT = 1,
  RESPONSE_PAYLOAD_FULL = 2,
  ResponsePayload_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  ResponsePayload_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t ResponsePayload_internal_data_[];
inline constexpr ResponsePayload ResponsePayload_MIN =
    static_cast<ResponsePayload>(0);
inline constexpr ResponsePayload ResponsePayload_MAX =
    static_cast<ResponsePayload>(2);
inline bool ResponsePayload_IsValid(int value) {
  return 0 <= value && value <= 2;
}
inline constexpr int ResponsePayload_ARRAYSIZE = 2 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL ResponsePayload_descriptor();
template <typename T>
const ::std::string& ResponsePayload_Name(T value) {
  static_assert(::std::is_same<T, ResponsePayload>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to ResponsePayload_Name().");
  return ResponsePayload_Name(static_cast<ResponsePayload>(value));
}
template <>
inline const ::std::string& ResponsePayload_Name(ResponsePayload value) {
  return ::google::protobuf::internal::NameOfDenseEnum<ResponsePayload_descriptor, 0, 2>(
      static_cast<int>(value));
}
inline bool ResponsePayload_Parse(
    ::absl::string_view name, ResponsePayload* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<ResponsePayload>(ResponsePayload_descriptor(), name,
                                           value);
}
enum Action : int {
  ACTION_UNSPECIFIED = 0,
  ACTION_LITERAL = 1,
  ACTION_DEFER = 2,
  Action_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  Action_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t Action_internal_data_[];
inline constexpr Action Action_MIN =
    static_cast<Action>(0);
inline constexpr Action Action_MAX =
    static_cast<Action>(2);
inline bool Action_IsValid(int value) {
  return 0 <= value && value <= 2;
}
inline constexpr int Action_ARRAYSIZE = 2 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL Action_descriptor();
template <typename T>
const ::std::string& Action_Name(T value) {
  static_assert(::std::is_same<T, Action>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to Action_Name().");
  return Action_Name(static_cast<Action>(value));
}
template <>
inline const ::std::string& Action_Name(Action value) {
  return ::google::protobuf::internal::NameOfDenseEnum<Action_descriptor, 0, 2>(
      static_cast<int>(value));
}
inline bool Action_Parse(
    ::absl::string_view name, Action* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<Action>(Action_descriptor(), name,
                                           value);
}

// ===================================================================


// -------------------------------------------------------------------

class BranchRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:satact_trace.BranchRequest) */ {
 public:
  inline BranchRequest() : BranchRequest(nullptr) {}
  ~BranchRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(BranchRequest* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(BranchRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR BranchRequest(::google::protobuf::internal::ConstantInitialized);

  inline BranchRequest(const BranchRequest& from) : BranchRequest(nullptr, from) {}
  inline BranchRequest(BranchRequest&& from) noexcept
      : BranchRequest(nullptr, ::std::move(from)) {}
  inline BranchRequest& operator=(const BranchRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline BranchRequest& operator=(BranchRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BranchRequest& default_instance() {
    return *reinterpret_cast<const BranchRequest*>(
        &_BranchRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(BranchRequest& a, BranchRequest& b) { a.Swap(&b); }
  inline void Swap(BranchRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BranchRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BranchRequest* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<BranchRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const BranchRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const BranchRequest& from) { BranchRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(BranchRequest* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "satact_trace.BranchRequest"; }

 protected:
  explicit BranchRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  BranchRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const BranchRequest& from);
  BranchRequest(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, BranchRequest&& from) noexcept
      : BranchRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kCIdxsFieldNumber = 3,
    kLIdxsFieldNumber = 4,
    kAssignmentValueFieldNumber = 5,
    kAssignmentLevelFieldNumber = 6,
    kCandidateVariableFieldNumber = 8,
    kModelVariantFieldNumber = 9,
    kNVarsFieldNumber = 1,
    kNClausesFieldNumber = 2,
    kDecisionLevelFieldNumber = 7,
    kResponsePayloadFieldNumber = 10,
  };
  // repeated int32 c_idxs = 3;
  int c_idxs_size() const;
  private:
  int _internal_c_idxs_size() const;

  public:
  void clear_c_idxs() ;
  ::int32_t c_idxs(int index) const;
  void set_c_idxs(int index, ::int32_t value);
  void add_c_idxs(::int32_t value);
  const ::google::protobuf::RepeatedField<::int32_t>& c_idxs() const;
  ::google::protobuf::RepeatedField<::int32_t>* PROTOBUF_NONNULL mutable_c_idxs();

  private:
  const ::google::protobuf::RepeatedField<::int32_t>& _internal_c_idxs() const;
  ::google::protobuf::RepeatedField<::int32_t>* PROTOBUF_NONNULL _internal_mutable_c_idxs();

  public:
  // repeated int32 l_idxs = 4;
  int l_idxs_size() const;
  private:
  int _internal_l_idxs_size() const;

  public:
  void clear_l_idxs() ;
  ::int32_t l_idxs(int index) const;
  void set_l_idxs(int index, ::int32_t value);
  void add_l_idxs(::int32_t value);
  const ::google::protobuf::RepeatedField<::int32_t>& l_idxs() const;
  ::google::protobuf::RepeatedField<::int32_t>* PROTOBUF_NONNULL mutable_l_idxs();

  private:
  const ::google::protobuf::RepeatedField<::int32_t>& _internal_l_idxs() const;
  ::google::protobuf::RepeatedField<::int32_t>* PROTOBUF_NONNULL _internal_mutable_l_idxs();

  public:
  // repeated int32 assignment_value = 5;
  int assignment_value_size() const;
  private:
  int _internal_assignment_value_size() const;

  public:
  void clear_assignment_value() ;
  ::int32_t assignment_value(int index) const;
  void set_assignment_value(int index, ::int32_t value);
  void add_assignment_value(::int32_t value);
  const ::google::protobuf::RepeatedField<::int32_t>& assignment_value() const;
  ::google::protobuf::RepeatedField<::int32_t>* PROTOBUF_NONNULL mutable_assignment_value();

  private:
  const ::google::protobuf::RepeatedField<::int32_t>& _internal_assignment_value() const;
  ::google::protobuf::RepeatedField<::int32_t>* PROTOBUF_NONNULL _internal_mutable_assignment_value();

  public:
  // repeated int32 assignment_level = 6;
  int assignment_level_size() const;
  private:
  int _internal_assignment_level_size() const;

  public:
  void clear_assignment_level() ;
  ::int32_t assignment_level(int index) const;
  void set_assignment_level(int index, ::int32_t value);
  void add_assignment_level(::int32_t value);
  const ::google::protobuf::RepeatedField<::int32_t>& assignment_level() const;
  ::google::protobuf::RepeatedField<::int32_t>* PROTOBUF_NONNULL mutable_assignment_level();

  private:
  const ::google::protobuf::RepeatedField<::int32_t>& _internal_assignment_level() const;
  ::google::protobuf::RepeatedField<::int32_t>* PROTOBUF_NONNULL _internal_mutable_assignment_level();

  public:
  // repeated bool candidate_variable = 8;
  int candidate_variable_size() const;
  private:
  int _internal_candidate_variable_size() const;

  public:
  void clear_candidate_variable() ;
  bool candidate_variable(int index) const;
  void set_candidate_variable(int index, bool value);
  void add_candidate_variable(bool value);
  const ::google::protobuf::RepeatedField<bool>& candidate_variable() const;
  ::google::protobuf::RepeatedField<bool>* PROTOBUF_NONNULL mutable_candidate_variable();

  private:
  const ::google::protobuf::RepeatedField<bool>& _internal_candidate_variable() const;
  ::google::protobuf::RepeatedField<bool>* PROTOBUF_NONNULL _internal_mutable_candidate_variable();

  public:
  // string model_variant = 9;
  void clear_model_variant() ;
  const ::std::string& model_variant() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_model_variant(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_model_variant();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_model_variant();
  void set_allocated_model_variant(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_model_variant() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_model_variant(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_model_variant();

  public:
  // int32 n_vars = 1;
  void clear_n_vars() ;
  ::int32_t n_vars() const;
  void set_n_vars(::int32_t value);

  private:
  ::int32_t _internal_n_vars() const;
  void _internal_set_n_vars(::int32_t value);

  public:
  // int32 n_clauses = 2;
  void clear_n_clauses() ;
  ::int32_t n_clauses() const;
  void set_n_clauses(::int32_t value);

  private:
  ::int32_t _internal_n_clauses() const;
  void _internal_set_n_clauses(::int32_t value);

  public:
  // int32 decision_level = 7;
  void clear_decision_level() ;
  ::int32_t decision_level() const;
  void set_decision_level(::int32_t value);

  private:
  ::int32_t _internal_decision_level() const;
  void _internal_set_decision_level(::int32_t value);

  public:
  // .satact_trace.ResponsePayload response_payload = 10;
  void clear_response_payload() ;
  ::satact_trace::ResponsePayload response_payload() const;
  void set_response_payload(::satact_trace::ResponsePayload value);

  private:
  ::satact_trace::ResponsePayload _internal_response_payload() const;
  void _internal_set_response_payload(::satact_trace::ResponsePayload value);

  public:
  // @@protoc_insertion_point(class_scope:satact_trace.BranchRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<4, 10,
                                   0, 56,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const BranchRequest& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedField<::int32_t> c_idxs_;
    ::google::protobuf::internal::CachedSize _c_idxs_cached_byte_size_;
    ::google::protobuf::RepeatedField<::int32_t> l_idxs_;
    ::google::protobuf::internal::CachedSize _l_idxs_cached_byte_size_;
    ::google::protobuf::RepeatedField<::int32_t> assignment_value_;
    ::google::protobuf::internal::CachedSize _assignment_value_cached_byte_size_;
    ::google::protobuf::RepeatedField<::int32_t> assignment_level_;
    ::google::protobuf::internal::CachedSize _assignment_level_cached_byte_size_;
    ::google::protobuf::RepeatedField<bool> candidate_variable_;
    ::google::protobuf::internal::ArenaStringPtr model_variant_;
    ::int32_t n_vars_;
    ::int32_t n_clauses_;
    ::int32_t decision_level_;
    int response_payload_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_satact_5ftrace_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull BranchRequest_class_data_;
// -------------------------------------------------------------------

class BranchDecision final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:satact_trace.BranchDecision) */ {
 public:
  inline BranchDecision() : BranchDecision(nullptr) {}
  ~BranchDecision() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(BranchDecision* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(BranchDecision));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR BranchDecision(::google::protobuf::internal::ConstantInitialized);

  inline BranchDecision(const BranchDecision& from) : BranchDecision(nullptr, from) {}
  inline BranchDecision(BranchDecision&& from) noexcept
      : BranchDecision(nullptr, ::std::move(from)) {}
  inline BranchDecision& operator=(const BranchDecision& from) {
    CopyFrom(from);
    return *this;
  }
  inline BranchDecision& operator=(BranchDecision&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BranchDecision& default_instance() {
    return *reinterpret_cast<const BranchDecision*>(
        &_BranchDecision_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(BranchDecision& a, BranchDecision& b) { a.Swap(&b); }
  inline void Swap(BranchDecision* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BranchDecision* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BranchDecision* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<BranchDecision>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const BranchDecision& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const BranchDecision& from) { BranchDecision::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(BranchDecision* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "satact_trace.BranchDecision"; }

 protected:
  explicit BranchDecision(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  BranchDecision(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const BranchDecision& from);
  BranchDecision(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, BranchDecision&& from) noexcept
      : BranchDecision(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kActionLogitsFieldNumber = 9,
    kMsgFieldNumber = 2,
    kModelVariantFieldNumber = 4,
    kSuccessFieldNumber = 1,
    kNSecsInferenceFieldNumber = 3,
    kActionFieldNumber = 5,
    kSelectedLiteralIndexFieldNumber = 6,
    kSelectedLogProbabilityFieldNumber = 7,
    kResponsePayloadFieldNumber = 8,
  };
  // repeated float action_logits = 9;
  int action_logits_size() const;
  private:
  int _internal_action_logits_size() const;

  public:
  void clear_action_logits() ;
  float action_logits(int index) const;
  void set_action_logits(int index, float value);
  void add_action_logits(float value);
  const ::google::protobuf::RepeatedField<float>& action_logits() const;
  ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL mutable_action_logits();

  private:
  const ::google::protobuf::RepeatedField<float>& _internal_action_logits() const;
  ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL _internal_mutable_action_logits();

  public:
  // string msg = 2;
  void clear_msg() ;
  const ::std::string& msg() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_msg(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_msg();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_msg();
  void set_allocated_msg(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_msg() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_msg(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_msg();

  public:
  // string model_variant = 4;
  void clear_model_variant() ;
  const ::std::string& model_variant() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_model_variant(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_model_variant();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_model_variant();
  void set_allocated_model_variant(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_model_variant() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_model_variant(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_model_variant();

  public:
  // bool success = 1;
  void clear_success() ;
  bool success() const;
  void set_success(bool value);

  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);

  public:
  // float n_secs_inference = 3;
  void clear_n_secs_inference() ;
  float n_secs_inference() const;
  void set_n_secs_inference(float value);

  private:
  float _internal_n_secs_inference() const;
  void _internal_set_n_secs_inference(float value);

  public:
  // .satact_trace.Action action = 5;
  void clear_action() ;
  ::satact_trace::Action action() const;
  void set_action(::satact_trace::Action value);

  private:
  ::satact_trace::Action _internal_action() const;
  void _internal_set_action(::satact_trace::Action value);

  public:
  // int32 selected_literal_index = 6;
  void clear_selected_literal_index() ;
  ::int32_t selected_literal_index() const;
  void set_selected_literal_index(::int32_t value);

  private:
  ::int32_t _internal_selected_literal_index() const;
  void _internal_set_selected_literal_index(::int32_t value);

  public:
  // float selected_log_probability = 7;
  void clear_selected_log_probability() ;
  float selected_log_probability() const;
  void set_selected_log_probability(float value);

  private:
  float _internal_selected_log_probability() const;
  void _internal_set_selected_log_probability(float value);

  public:
  // .satact_trace.ResponsePayload response_payload = 8;
  void clear_response_payload() ;
  ::satact_trace::ResponsePayload response_payload() const;
  void set_response_payload(::satact_trace::ResponsePayload value);

  private:
  ::satact_trace::ResponsePayload _internal_response_payload() const;
  void _internal_set_response_payload(::satact_trace::ResponsePayload value);

  public:
  // @@protoc_insertion_point(class_scope:satact_trace.BranchDecision)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<4, 9,
                                   0, 60,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const BranchDecision& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedField<float> action_logits_;
    ::google::protobuf::internal::ArenaStringPtr msg_;
    ::google::protobuf::internal::ArenaStringPtr model_variant_;
    bool success_;
    float n_secs_inference_;
    int action_;
    ::int32_t selected_literal_index_;
    float selected_log_probability_;
    int response_payload_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_satact_5ftrace_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull BranchDecision_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// BranchRequest

// int32 n_vars = 1;
inline void BranchRequest::clear_n_vars() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.n_vars_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline ::int32_t BranchRequest::n_vars() const {
  // @@protoc_insertion_point(field_get:satact_trace.BranchRequest.n_vars)
  return _internal_n_vars();
}
inline void BranchRequest::set_n_vars(::int32_t value) {
  _internal_set_n_vars(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:satact_trace.BranchRequest.n_vars)
}
inline ::int32_t BranchRequest::_internal_n_vars() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.n_vars_;
}
inline void BranchRequest::_internal_set_n_vars(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.n_vars_ = value;
}

// int32 n_clauses = 2;
inline void BranchRequest::clear_n_clauses() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.n_clauses_ = 0;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline ::int32_t BranchRequest::n_clauses() const {
  // @@protoc_insertion_point(field_get:satact_trace.BranchRequest.n_clauses)
  return _internal_n_clauses();
}
inline void BranchRequest::set_n_clauses(::int32_t value) {
  _internal_set_n_clauses(value);
  _impl_._has_bits_[0] |= 0x00000004u;
  // @@protoc_insertion_point(field_set:satact_trace.BranchRequest.n_clauses)
}
inline ::int32_t BranchRequest::_internal_n_clauses() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.n_clauses_;
}
inline void BranchRequest::_internal_set_n_clauses(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.n_clauses_ = value;
}

// repeated int32 c_idxs = 3;
inline int BranchRequest::_internal_c_idxs_size() const {
  return _internal_c_idxs().size();
}
inline int BranchRequest::c_idxs_size() const {
  return _internal_c_idxs_size();
}
inline void BranchRequest::clear_c_idxs() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.c_idxs_.Clear();
}
inline ::int32_t BranchRequest::c_idxs(int index) const {
  // @@protoc_insertion_point(field_get:satact_trace.BranchRequest.c_idxs)
  return _internal_c_idxs().Get(index);
}
inline void BranchRequest::set_c_idxs(int index, ::int32_t value) {
  _internal_mutable_c_idxs()->Set(index, value);
  // @@protoc_insertion_point(field_set:satact_trace.BranchRequest.c_idxs)
}
inline void BranchRequest::add_c_idxs(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_c_idxs()->Add(value);
  // @@protoc_insertion_point(field_add:satact_trace.BranchRequest.c_idxs)
}
inline const ::google::protobuf::RepeatedField<::int32_t>& BranchRequest::c_idxs() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:satact_trace.BranchRequest.c_idxs)
  return _internal_c_idxs();
}
inline ::google::protobuf::RepeatedField<::int32_t>* PROTOBUF_NONNULL BranchRequest::mutable_c_idxs()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:satact_trace.BranchRequest.c_idxs)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_c_idxs();
}
inline const ::google::protobuf::RepeatedField<::int32_t>&
BranchRequest::_internal_c_idxs() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.c_idxs_;
}
inline ::google::protobuf::RepeatedField<::int32_t>* PROTOBUF_NONNULL
BranchRequest::_internal_mutable_c_idxs() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.c_idxs_;
}

// repeated int32 l_idxs = 4;
inline int BranchRequest::_internal_l_idxs_size() const {
  return _internal_l_idxs().size();
}
inline int BranchRequest::l_idxs_size() const {
  return _internal_l_idxs_size();
}
inline void BranchRequest::clear_l_idxs() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.l_idxs_.Clear();
}
inline ::int32_t BranchRequest::l_idxs(int index) const {
  // @@protoc_insertion_point(field_get:satact_trace.BranchRequest.l_idxs)
  return _internal_l_idxs().Get(index);
}
inline void BranchRequest::set_l_idxs(int index, ::int32_t value) {
  _internal_mutable_l_idxs()->Set(index, value);
  // @@protoc_insertion_point(field_set:satact_trace.BranchRequest.l_idxs)
}
inline void BranchRequest::add_l_idxs(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_l_idxs()->Add(value);
  // @@protoc_insertion_point(field_add:satact_trace.BranchRequest.l_idxs)
}
inline const ::google::protobuf::RepeatedField<::int32_t>& BranchRequest::l_idxs() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:satact_trace.BranchRequest.l_idxs)
  return _internal_l_idxs();
}
inline ::google::protobuf::RepeatedField<::int32_t>* PROTOBUF_NONNULL BranchRequest::mutable_l_idxs()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:satact_trace.BranchRequest.l_idxs)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_l_idxs();
}
inline const ::google::protobuf::RepeatedField<::int32_t>&
BranchRequest::_internal_l_idxs() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.l_idxs_;
}
inline ::google::protobuf::RepeatedField<::int32_t>* PROTOBUF_NONNULL
BranchRequest::_internal_mutable_l_idxs() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.l_idxs_;
}

// repeated int32 assignment_value = 5;
inline int BranchRequest::_internal_assignment_value_size() const {
  return _internal_assignment_value().size();
}
inline int BranchRequest::assignment_value_size() const {
  return _internal_assignment_value_size();
}
inline void BranchRequest::clear_assignment_value() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.assignment_value_.Clear();
}
inline ::int32_t BranchRequest::assignment_value(int index) const {
  // @@protoc_insertion_point(field_get:satact_trace.BranchRequest.assignment_value)
  return _internal_assignment_value().Get(index);
}
inline void BranchRequest::set_assignment_value(int index, ::int32_t value) {
  _internal_mutable_assignment_value()->Set(index, value);
  // @@protoc_insertion_point(field_set:satact_trace.BranchRequest.assignment_value)
}
inline void BranchRequest::add_assignment_value(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_assignment_value()->Add(value);
  // @@protoc_insertion_point(field_add:satact_trace.BranchRequest.assignment_value)
}
inline const ::google::protobuf::RepeatedField<::int32_t>& BranchRequest::assignment_value() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:satact_trace.BranchRequest.assignment_value)
  return _internal_assignment_value();
}
inline ::google::protobuf::RepeatedField<::int32_t>* PROTOBUF_NONNULL BranchRequest::mutable_assignment_value()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:satact_trace.BranchRequest.assignment_value)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_assignment_value();
}
inline const ::google::protobuf::RepeatedField<::int32_t>&
BranchRequest::_internal_assignment_value() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.assignment_value_;
}
inline ::google::protobuf::RepeatedField<::int32_t>* PROTOBUF_NONNULL
BranchRequest::_internal_mutable_assignment_value() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.assignment_value_;
}

// repeated int32 assignment_level = 6;
inline int BranchRequest::_internal_assignment_level_size() const {
  return _internal_assignment_level().size();
}
inline int BranchRequest::assignment_level_size() const {
  return _internal_assignment_level_size();
}
inline void BranchRequest::clear_assignment_level() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.assignment_level_.Clear();
}
inline ::int32_t BranchRequest::assignment_level(int index) const {
  // @@protoc_insertion_point(field_get:satact_trace.BranchRequest.assignment_level)
  return _internal_assignment_level().Get(index);
}
inline void BranchRequest::set_assignment_level(int index, ::int32_t value) {
  _internal_mutable_assignment_level()->Set(index, value);
  // @@protoc_insertion_point(field_set:satact_trace.BranchRequest.assignment_level)
}
inline void BranchRequest::add_assignment_level(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_assignment_level()->Add(value);
  // @@protoc_insertion_point(field_add:satact_trace.BranchRequest.assignment_level)
}
inline const ::google::protobuf::RepeatedField<::int32_t>& BranchRequest::assignment_level() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:satact_trace.BranchRequest.assignment_level)
  return _internal_assignment_level();
}
inline ::google::protobuf::RepeatedField<::int32_t>* PROTOBUF_NONNULL BranchRequest::mutable_assignment_level()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:satact_trace.BranchRequest.assignment_level)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_assignment_level();
}
inline const ::google::protobuf::RepeatedField<::int32_t>&
BranchRequest::_internal_assignment_level() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.assignment_level_;
}
inline ::google::protobuf::RepeatedField<::int32_t>* PROTOBUF_NONNULL
BranchRequest::_internal_mutable_assignment_level() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.assignment_level_;
}

// int32 decision_level = 7;
inline void BranchRequest::clear_decision_level() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.decision_level_ = 0;
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline ::int32_t BranchRequest::decision_level() const {
  // @@protoc_insertion_point(field_get:satact_trace.BranchRequest.decision_level)
  return _internal_decision_level();
}
inline void BranchRequest::set_decision_level(::int32_t value) {
  _internal_set_decision_level(value);
  _impl_._has_bits_[0] |= 0x00000008u;
  // @@protoc_insertion_point(field_set:satact_trace.BranchRequest.decision_level)
}
inline ::int32_t BranchRequest::_internal_decision_level() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.decision_level_;
}
inline void BranchRequest::_internal_set_decision_level(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.decision_level_ = value;
}

// repeated bool candidate_variable = 8;
inline int BranchRequest::_internal_candidate_variable_size() const {
  return _internal_candidate_variable().size();
}
inline int BranchRequest::candidate_variable_size() const {
  return _internal_candidate_variable_size();
}
inline void BranchRequest::clear_candidate_variable() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.candidate_variable_.Clear();
}
inline bool BranchRequest::candidate_variable(int index) const {
  // @@protoc_insertion_point(field_get:satact_trace.BranchRequest.candidate_variable)
  return _internal_candidate_variable().Get(index);
}
inline void BranchRequest::set_candidate_variable(int index, bool value) {
  _internal_mutable_candidate_variable()->Set(index, value);
  // @@protoc_insertion_point(field_set:satact_trace.BranchRequest.candidate_variable)
}
inline void BranchRequest::add_candidate_variable(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_candidate_variable()->Add(value);
  // @@protoc_insertion_point(field_add:satact_trace.BranchRequest.candidate_variable)
}
inline const ::google::protobuf::RepeatedField<bool>& BranchRequest::candidate_variable() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:satact_trace.BranchRequest.candidate_variable)
  return _internal_candidate_variable();
}
inline ::google::protobuf::RepeatedField<bool>* PROTOBUF_NONNULL BranchRequest::mutable_candidate_variable()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:satact_trace.BranchRequest.candidate_variable)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_candidate_variable();
}
inline const ::google::protobuf::RepeatedField<bool>&
BranchRequest::_internal_candidate_variable() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.candidate_variable_;
}
inline ::google::protobuf::RepeatedField<bool>* PROTOBUF_NONNULL
BranchRequest::_internal_mutable_candidate_variable() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.candidate_variable_;
}

// string model_variant = 9;
inline void BranchRequest::clear_model_variant() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.model_variant_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::std::string& BranchRequest::model_variant() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:satact_trace.BranchRequest.model_variant)
  return _internal_model_variant();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void BranchRequest::set_model_variant(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.model_variant_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:satact_trace.BranchRequest.model_variant)
}
inline ::std::string* PROTOBUF_NONNULL BranchRequest::mutable_model_variant()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_model_variant();
  // @@protoc_insertion_point(field_mutable:satact_trace.BranchRequest.model_variant)
  return _s;
}
inline const ::std::string& BranchRequest::_internal_model_variant() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.model_variant_.Get();
}
inline void BranchRequest::_internal_set_model_variant(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.model_variant_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL BranchRequest::_internal_mutable_model_variant() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.model_variant_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE BranchRequest::release_model_variant() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:satact_trace.BranchRequest.model_variant)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.model_variant_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.model_variant_.Set("", GetArena());
  }
  return released;
}
inline void BranchRequest::set_allocated_model_variant(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.model_variant_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.model_variant_.IsDefault()) {
    _impl_.model_variant_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:satact_trace.BranchRequest.model_variant)
}

// .satact_trace.ResponsePayload response_payload = 10;
inline void BranchRequest::clear_response_payload() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.response_payload_ = 0;
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline ::satact_trace::ResponsePayload BranchRequest::response_payload() const {
  // @@protoc_insertion_point(field_get:satact_trace.BranchRequest.response_payload)
  return _internal_response_payload();
}
inline void BranchRequest::set_response_payload(::satact_trace::ResponsePayload value) {
  _internal_set_response_payload(value);
  _impl_._has_bits_[0] |= 0x00000010u;
  // @@protoc_insertion_point(field_set:satact_trace.BranchRequest.response_payload)
}
inline ::satact_trace::ResponsePayload BranchRequest::_internal_response_payload() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::satact_trace::ResponsePayload>(_impl_.response_payload_);
}
inline void BranchRequest::_internal_set_response_payload(::satact_trace::ResponsePayload value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.response_payload_ = value;
}

// -------------------------------------------------------------------

// BranchDecision

// bool success = 1;
inline void BranchDecision::clear_success() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.success_ = false;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline bool BranchDecision::success() const {
  // @@protoc_insertion_point(field_get:satact_trace.BranchDecision.success)
  return _internal_success();
}
inline void BranchDecision::set_success(bool value) {
  _internal_set_success(value);
  _impl_._has_bits_[0] |= 0x00000004u;
  // @@protoc_insertion_point(field_set:satact_trace.BranchDecision.success)
}
inline bool BranchDecision::_internal_success() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.success_;
}
inline void BranchDecision::_internal_set_success(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.success_ = value;
}

// string msg = 2;
inline void BranchDecision::clear_msg() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.msg_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::std::string& BranchDecision::msg() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:satact_trace.BranchDecision.msg)
  return _internal_msg();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void BranchDecision::set_msg(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.msg_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:satact_trace.BranchDecision.msg)
}
inline ::std::string* PROTOBUF_NONNULL BranchDecision::mutable_msg()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_msg();
  // @@protoc_insertion_point(field_mutable:satact_trace.BranchDecision.msg)
  return _s;
}
inline const ::std::string& BranchDecision::_internal_msg() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.msg_.Get();
}
inline void BranchDecision::_internal_set_msg(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.msg_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL BranchDecision::_internal_mutable_msg() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.msg_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE BranchDecision::release_msg() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:satact_trace.BranchDecision.msg)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.msg_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.msg_.Set("", GetArena());
  }
  return released;
}
inline void BranchDecision::set_allocated_msg(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.msg_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.msg_.IsDefault()) {
    _impl_.msg_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:satact_trace.BranchDecision.msg)
}

// float n_secs_inference = 3;
inline void BranchDecision::clear_n_secs_inference() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.n_secs_inference_ = 0;
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline float BranchDecision::n_secs_inference() const {
  // @@protoc_insertion_point(field_get:satact_trace.BranchDecision.n_secs_inference)
  return _internal_n_secs_inference();
}
inline void BranchDecision::set_n_secs_inference(float value) {
  _internal_set_n_secs_inference(value);
  _impl_._has_bits_[0] |= 0x00000008u;
  // @@protoc_insertion_point(field_set:satact_trace.BranchDecision.n_secs_inference)
}
inline float BranchDecision::_internal_n_secs_inference() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.n_secs_inference_;
}
inline void BranchDecision::_internal_set_n_secs_inference(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.n_secs_inference_ = value;
}

// string model_variant = 4;
inline void BranchDecision::clear_model_variant() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.model_variant_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const ::std::string& BranchDecision::model_variant() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:satact_trace.BranchDecision.model_variant)
  return _internal_model_variant();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void BranchDecision::set_model_variant(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.model_variant_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:satact_trace.BranchDecision.model_variant)
}
inline ::std::string* PROTOBUF_NONNULL BranchDecision::mutable_model_variant()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::std::string* _s = _internal_mutable_model_variant();
  // @@protoc_insertion_point(field_mutable:satact_trace.BranchDecision.model_variant)
  return _s;
}
inline const ::std::string& BranchDecision::_internal_model_variant() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.model_variant_.Get();
}
inline void BranchDecision::_internal_set_model_variant(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.model_variant_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL BranchDecision::_internal_mutable_model_variant() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.model_variant_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE BranchDecision::release_model_variant() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:satact_trace.BranchDecision.model_variant)
  if ((_impl_._has_bits_[0] & 0x00000002u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* released = _impl_.model_variant_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.model_variant_.Set("", GetArena());
  }
  return released;
}
inline void BranchDecision::set_allocated_model_variant(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.model_variant_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.model_variant_.IsDefault()) {
    _impl_.model_variant_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:satact_trace.BranchDecision.model_variant)
}

// .satact_trace.Action action = 5;
inline void BranchDecision::clear_action() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.action_ = 0;
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline ::satact_trace::Action BranchDecision::action() const {
  // @@protoc_insertion_point(field_get:satact_trace.BranchDecision.action)
  return _internal_action();
}
inline void BranchDecision::set_action(::satact_trace::Action value) {
  _internal_set_action(value);
  _impl_._has_bits_[0] |= 0x00000010u;
  // @@protoc_insertion_point(field_set:satact_trace.BranchDecision.action)
}
inline ::satact_trace::Action BranchDecision::_internal_action() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::satact_trace::Action>(_impl_.action_);
}
inline void BranchDecision::_internal_set_action(::satact_trace::Action value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.action_ = value;
}

// int32 selected_literal_index = 6;
inline void BranchDecision::clear_selected_literal_index() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.selected_literal_index_ = 0;
  _impl_._has_bits_[0] &= ~0x00000020u;
}
inline ::int32_t BranchDecision::selected_literal_index() const {
  // @@protoc_insertion_point(field_get:satact_trace.BranchDecision.selected_literal_index)
  return _internal_selected_literal_index();
}
inline void BranchDecision::set_selected_literal_index(::int32_t value) {
  _internal_set_selected_literal_index(value);
  _impl_._has_bits_[0] |= 0x00000020u;
  // @@protoc_insertion_point(field_set:satact_trace.BranchDecision.selected_literal_index)
}
inline ::int32_t BranchDecision::_internal_selected_literal_index() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.selected_literal_index_;
}
inline void BranchDecision::_internal_set_selected_literal_index(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.selected_literal_index_ = value;
}

// float selected_log_probability = 7;
inline void BranchDecision::clear_selected_log_probability() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.selected_log_probability_ = 0;
  _impl_._has_bits_[0] &= ~0x00000040u;
}
inline float BranchDecision::selected_log_probability() const {
  // @@protoc_insertion_point(field_get:satact_trace.BranchDecision.selected_log_probability)
  return _internal_selected_log_probability();
}
inline void BranchDecision::set_selected_log_probability(float value) {
  _internal_set_selected_log_probability(value);
  _impl_._has_bits_[0] |= 0x00000040u;
  // @@protoc_insertion_point(field_set:satact_trace.BranchDecision.selected_log_probability)
}
inline float BranchDecision::_internal_selected_log_probability() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.selected_log_probability_;
}
inline void BranchDecision::_internal_set_selected_log_probability(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.selected_log_probability_ = value;
}

// .satact_trace.ResponsePayload response_payload = 8;
inline void BranchDecision::clear_response_payload() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.response_payload_ = 0;
  _impl_._has_bits_[0] &= ~0x00000080u;
}
inline ::satact_trace::ResponsePayload BranchDecision::response_payload() const {
  // @@protoc_insertion_point(field_get:satact_trace.BranchDecision.response_payload)
  return _internal_response_payload();
}
inline void BranchDecision::set_response_payload(::satact_trace::ResponsePayload value) {
  _internal_set_response_payload(value);
  _impl_._has_bits_[0] |= 0x00000080u;
  // @@protoc_insertion_point(field_set:satact_trace.BranchDecision.response_payload)
}
inline ::satact_trace::ResponsePayload BranchDecision::_internal_response_payload() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::satact_trace::ResponsePayload>(_impl_.response_payload_);
}
inline void BranchDecision::_internal_set_response_payload(::satact_trace::ResponsePayload value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.response_payload_ = value;
}

// repeated float action_logits = 9;
inline int BranchDecision::_internal_action_logits_size() const {
  return _internal_action_logits().size();
}
inline int BranchDecision::action_logits_size() const {
  return _internal_action_logits_size();
}
inline void BranchDecision::clear_action_logits() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.action_logits_.Clear();
}
inline float BranchDecision::action_logits(int index) const {
  // @@protoc_insertion_point(field_get:satact_trace.BranchDecision.action_logits)
  return _internal_action_logits().Get(index);
}
inline void BranchDecision::set_action_logits(int index, float value) {
  _internal_mutable_action_logits()->Set(index, value);
  // @@protoc_insertion_point(field_set:satact_trace.BranchDecision.action_logits)
}
inline void BranchDecision::add_action_logits(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_action_logits()->Add(value);
  // @@protoc_insertion_point(field_add:satact_trace.BranchDecision.action_logits)
}
inline const ::google::protobuf::RepeatedField<float>& BranchDecision::action_logits() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:satact_trace.BranchDecision.action_logits)
  return _internal_action_logits();
}
inline ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL BranchDecision::mutable_action_logits()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:satact_trace.BranchDecision.action_logits)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_action_logits();
}
inline const ::google::protobuf::RepeatedField<float>&
BranchDecision::_internal_action_logits() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.action_logits_;
}
inline ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL
BranchDecision::_internal_mutable_action_logits() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.action_logits_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace satact_trace


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::satact_trace::ResponsePayload> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::satact_trace::ResponsePayload>() {
  return ::satact_trace::ResponsePayload_descriptor();
}
template <>
struct is_proto_enum<::satact_trace::Action> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::satact_trace::Action>() {
  return ::satact_trace::Action_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // satact_5ftrace_2eproto_2epb_2eh
