// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: satact_trace.proto
// Protobuf C++ Version: 6.31.1

#include "satact_trace.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace satact_trace {

inline constexpr BranchRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        c_idxs_{},
        _c_idxs_cached_byte_size_{0},
        l_idxs_{},
        _l_idxs_cached_byte_size_{0},
        assignment_value_{},
        _assignment_value_cached_byte_size_{0},
        assignment_level_{},
        _assignment_level_cached_byte_size_{0},
        candidate_variable_{},
        model_variant_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        n_vars_{0},
        n_clauses_{0},
        decision_level_{0},
        response_payload_{static_cast< ::satact_trace::ResponsePayload >(0)} {}

template <typename>
PROTOBUF_CONSTEXPR BranchRequest::BranchRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(BranchRequest_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct BranchRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BranchRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~BranchRequestDefaultTypeInternal() {}
  union {
    BranchRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BranchRequestDefaultTypeInternal _BranchRequest_default_instance_;

inline constexpr BranchDecision::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        action_logits_{},
        msg_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        model_variant_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        success_{false},
        n_secs_inference_{0},
        action_{static_cast< ::satact_trace::Action >(0)},
        selected_literal_index_{0},
        selected_log_probability_{0},
        response_payload_{static_cast< ::satact_trace::ResponsePayload >(0)} {}

template <typename>
PROTOBUF_CONSTEXPR BranchDecision::BranchDecision(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(BranchDecision_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct BranchDecisionDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BranchDecisionDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~BranchDecisionDefaultTypeInternal() {}
  union {
    BranchDecision _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BranchDecisionDefaultTypeInternal _BranchDecision_default_instance_;
}  // namespace satact_trace
static const ::_pb::EnumDescriptor* PROTOBUF_NONNULL
    file_level_enum_descriptors_satact_5ftrace_2eproto[2];
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_satact_5ftrace_2eproto = nullptr;
const ::uint32_t
    TableStruct_satact_5ftrace_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::satact_trace::BranchRequest, _impl_._has_bits_),
        13, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::satact_trace::BranchRequest, _impl_.n_vars_),
        PROTOBUF_FIELD_OFFSET(::satact_trace::BranchRequest, _impl_.n_clauses_),
        PROTOBUF_FIELD_OFFSET(::satact_trace::BranchRequest, _impl_.c_idxs_),
        PROTOBUF_FIELD_OFFSET(::satact_trace::BranchRequest, _impl_.l_idxs_),
        PROTOBUF_FIELD_OFFSET(::satact_trace::BranchRequest, _impl_.assignment_value_),
        PROTOBUF_FIELD_OFFSET(::satact_trace::BranchRequest, _impl_.assignment_level_),
        PROTOBUF_FIELD_OFFSET(::satact_trace::BranchRequest, _impl_.decision_level_),
        PROTOBUF_FIELD_OFFSET(::satact_trace::BranchRequest, _impl_.candidate_variable_),
        PROTOBUF_FIELD_OFFSET(::satact_trace::BranchRequest, _impl_.model_variant_),
        PROTOBUF_FIELD_OFFSET(::satact_trace::BranchRequest, _impl_.response_payload_),
        1,
        2,
        ~0u,
        ~0u,
        ~0u,
        ~0u,
        3,
        ~0u,
        0,
        4,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::satact_trace::BranchDecision, _impl_._has_bits_),
        12, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::satact_trace::BranchDecision, _impl_.success_),
        PROTOBUF_FIELD_OFFSET(::satact_trace::BranchDecision, _impl_.msg_),
        PROTOBUF_FIELD_OFFSET(::satact_trace::BranchDecision, _impl_.n_secs_inference_),
        PROTOBUF_FIELD_OFFSET(::satact_trace::BranchDecision, _impl_.model_variant_),
        PROTOBUF_FIELD_OFFSET(::satact_trace::BranchDecision, _impl_.action_),
        PROTOBUF_FIELD_OFFSET(::satact_trace::BranchDecision, _impl_.selected_literal_index_),
        PROTOBUF_FIELD_OFFSET(::satact_trace::BranchDecision, _impl_.selected_log_probability_),
        PROTOBUF_FIELD_OFFSET(::satact_trace::BranchDecision, _impl_.response_payload_),
        PROTOBUF_FIELD_OFFSET(::satact_trace::BranchDecision, _impl_.action_logits_),
        2,
        0,
        3,
        1,
        4,
        5,
        6,
        7,
        ~0u,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::satact_trace::BranchRequest)},
        {23, sizeof(::satact_trace::BranchDecision)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::satact_trace::_BranchRequest_default_instance_._instance,
    &::satact_trace::_BranchDecision_default_instance_._instance,
};
const char descriptor_table_protodef_satact_5ftrace_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\022satact_trace.proto\022\014satact_trace\"\212\002\n\rB"
    "ranchRequest\022\016\n\006n_vars\030\001 \001(\005\022\021\n\tn_clause"
    "s\030\002 \001(\005\022\016\n\006c_idxs\030\003 \003(\005\022\016\n\006l_idxs\030\004 \003(\005\022"
    "\030\n\020assignment_value\030\005 \003(\005\022\030\n\020assignment_"
    "level\030\006 \003(\005\022\026\n\016decision_level\030\007 \001(\005\022\032\n\022c"
    "andidate_variable\030\010 \003(\010\022\025\n\rmodel_variant"
    "\030\t \001(\t\0227\n\020response_payload\030\n \001(\0162\035.satac"
    "t_trace.ResponsePayload\"\227\002\n\016BranchDecisi"
    "on\022\017\n\007success\030\001 \001(\010\022\013\n\003msg\030\002 \001(\t\022\030\n\020n_se"
    "cs_inference\030\003 \001(\002\022\025\n\rmodel_variant\030\004 \001("
    "\t\022$\n\006action\030\005 \001(\0162\024.satact_trace.Action\022"
    "\036\n\026selected_literal_index\030\006 \001(\005\022 \n\030selec"
    "ted_log_probability\030\007 \001(\002\0227\n\020response_pa"
    "yload\030\010 \001(\0162\035.satact_trace.ResponsePaylo"
    "ad\022\025\n\raction_logits\030\t \003(\002*l\n\017ResponsePay"
    "load\022 \n\034RESPONSE_PAYLOAD_UNSPECIFIED\020\000\022\034"
    "\n\030RESPONSE_PAYLOAD_COMPACT\020\001\022\031\n\025RESPONSE"
    "_PAYLOAD_FULL\020\002*F\n\006Action\022\026\n\022ACTION_UNSP"
    "ECIFIED\020\000\022\022\n\016ACTION_LITERAL\020\001\022\020\n\014ACTION_"
    "DEFER\020\0022`\n\021SATActTraceServer\022K\n\014query_br"
    "anch\022\033.satact_trace.BranchRequest\032\034.sata"
    "ct_trace.BranchDecision\"\000b\006proto3"
};
static ::absl::once_flag descriptor_table_satact_5ftrace_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_satact_5ftrace_2eproto = {
    false,
    false,
    873,
    descriptor_table_protodef_satact_5ftrace_2eproto,
    "satact_trace.proto",
    &descriptor_table_satact_5ftrace_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_satact_5ftrace_2eproto::offsets,
    file_level_enum_descriptors_satact_5ftrace_2eproto,
    file_level_service_descriptors_satact_5ftrace_2eproto,
};
namespace satact_trace {
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL ResponsePayload_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_satact_5ftrace_2eproto);
  return file_level_enum_descriptors_satact_5ftrace_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t ResponsePayload_internal_data_[] = {
    196608u, 0u, };
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL Action_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_satact_5ftrace_2eproto);
  return file_level_enum_descriptors_satact_5ftrace_2eproto[1];
}
PROTOBUF_CONSTINIT const uint32_t Action_internal_data_[] = {
    196608u, 0u, };
// ===================================================================

class BranchRequest::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<BranchRequest>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(BranchRequest, _impl_._has_bits_);
};

BranchRequest::BranchRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, BranchRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:satact_trace.BranchRequest)
}
PROTOBUF_NDEBUG_INLINE BranchRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::satact_trace::BranchRequest& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        c_idxs_{visibility, arena, from.c_idxs_},
        _c_idxs_cached_byte_size_{0},
        l_idxs_{visibility, arena, from.l_idxs_},
        _l_idxs_cached_byte_size_{0},
        assignment_value_{visibility, arena, from.assignment_value_},
        _assignment_value_cached_byte_size_{0},
        assignment_level_{visibility, arena, from.assignment_level_},
        _assignment_level_cached_byte_size_{0},
        candidate_variable_{visibility, arena, from.candidate_variable_},
        model_variant_(arena, from.model_variant_) {}

BranchRequest::BranchRequest(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const BranchRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, BranchRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  BranchRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, n_vars_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, n_vars_),
           offsetof(Impl_, response_payload_) -
               offsetof(Impl_, n_vars_) +
               sizeof(Impl_::response_payload_));

  // @@protoc_insertion_point(copy_constructor:satact_trace.BranchRequest)
}
PROTOBUF_NDEBUG_INLINE BranchRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        c_idxs_{visibility, arena},
        _c_idxs_cached_byte_size_{0},
        l_idxs_{visibility, arena},
        _l_idxs_cached_byte_size_{0},
        assignment_value_{visibility, arena},
        _assignment_value_cached_byte_size_{0},
        assignment_level_{visibility, arena},
        _assignment_level_cached_byte_size_{0},
        candidate_variable_{visibility, arena},
        model_variant_(arena) {}

inline void BranchRequest::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, n_vars_),
           0,
           offsetof(Impl_, response_payload_) -
               offsetof(Impl_, n_vars_) +
               sizeof(Impl_::response_payload_));
}
BranchRequest::~BranchRequest() {
  // @@protoc_insertion_point(destructor:satact_trace.BranchRequest)
  SharedDtor(*this);
}
inline void BranchRequest::SharedDtor(MessageLite& self) {
  BranchRequest& this_ = static_cast<BranchRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.model_variant_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL BranchRequest::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) BranchRequest(arena);
}
constexpr auto BranchRequest::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(BranchRequest, _impl_.c_idxs_) +
          decltype(BranchRequest::_impl_.c_idxs_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(BranchRequest, _impl_.l_idxs_) +
          decltype(BranchRequest::_impl_.l_idxs_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(BranchRequest, _impl_.assignment_value_) +
          decltype(BranchRequest::_impl_.assignment_value_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(BranchRequest, _impl_.assignment_level_) +
          decltype(BranchRequest::_impl_.assignment_level_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(BranchRequest, _impl_.candidate_variable_) +
          decltype(BranchRequest::_impl_.candidate_variable_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(BranchRequest), alignof(BranchRequest), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&BranchRequest::PlacementNew_,
                                 sizeof(BranchRequest),
                                 alignof(BranchRequest));
  }
}
constexpr auto BranchRequest::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_BranchRequest_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &BranchRequest::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<BranchRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &BranchRequest::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<BranchRequest>(), &BranchRequest::ByteSizeLong,
              &BranchRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(BranchRequest, _impl_._cached_size_),
          false,
      },
      &BranchRequest::kDescriptorMethods,
      &descriptor_table_satact_5ftrace_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull BranchRequest_class_data_ =
        BranchRequest::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
BranchRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&BranchRequest_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(BranchRequest_class_data_.tc_table);
  return BranchRequest_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<4, 10, 0, 56, 2>
BranchRequest::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(BranchRequest, _impl_._has_bits_),
    0, // no _extensions_
    10, 120,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294966272,  // skipmap
    offsetof(decltype(_table_), field_entries),
    10,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    BranchRequest_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::satact_trace::BranchRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int32 n_vars = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(BranchRequest, _impl_.n_vars_), 1>(),
     {8, 1, 0, PROTOBUF_FIELD_OFFSET(BranchRequest, _impl_.n_vars_)}},
    // int32 n_clauses = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(BranchRequest, _impl_.n_clauses_), 2>(),
     {16, 2, 0, PROTOBUF_FIELD_OFFSET(BranchRequest, _impl_.n_clauses_)}},
    // repeated int32 c_idxs = 3;
    {::_pbi::TcParser::FastV32P1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(BranchRequest, _impl_.c_idxs_)}},
    // repeated int32 l_idxs = 4;
    {::_pbi::TcParser::FastV32P1,
     {34, 63, 0, PROTOBUF_FIELD_OFFSET(BranchRequest, _impl_.l_idxs_)}},
    // repeated int32 assignment_value = 5;
    {::_pbi::TcParser::FastV32P1,
     {42, 63, 0, PROTOBUF_FIELD_OFFSET(BranchRequest, _impl_.assignment_value_)}},
    // repeated int32 assignment_level = 6;
    {::_pbi::TcParser::FastV32P1,
     {50, 63, 0, PROTOBUF_FIELD_OFFSET(BranchRequest, _impl_.assignment_level_)}},
    // int32 decision_level = 7;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(BranchRequest, _impl_.decision_level_), 3>(),
     {56, 3, 0, PROTOBUF_FIELD_OFFSET(BranchRequest, _impl_.decision_level_)}},
    // repeated bool candidate_variable = 8;
    {::_pbi::TcParser::FastV8P1,
     {66, 63, 0, PROTOBUF_FIELD_OFFSET(BranchRequest, _impl_.candidate_variable_)}},
    // string model_variant = 9;
    {::_pbi::TcParser::FastUS1,
     {74, 0, 0, PROTOBUF_FIELD_OFFSET(BranchRequest, _impl_.model_variant_)}},
    // .satact_trace.ResponsePayload response_payload = 10;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(BranchRequest, _impl_.response_payload_), 4>(),
     {80, 4, 0, PROTOBUF_FIELD_OFFSET(BranchRequest, _impl_.response_payload_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 n_vars = 1;
    {PROTOBUF_FIELD_OFFSET(BranchRequest, _impl_.n_vars_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // int32 n_clauses = 2;
    {PROTOBUF_FIELD_OFFSET(BranchRequest, _impl_.n_clauses_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // repeated int32 c_idxs = 3;
    {PROTOBUF_FIELD_OFFSET(BranchRequest, _impl_.c_idxs_), -1, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedInt32)},
    // repeated int32 l_idxs = 4;
    {PROTOBUF_FIELD_OFFSET(BranchRequest, _impl_.l_idxs_), -1, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedInt32)},
    // repeated int32 assignment_value = 5;
    {PROTOBUF_FIELD_OFFSET(BranchRequest, _impl_.assignment_value_), -1, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedInt32)},
    // repeated int32 assignment_level = 6;
    {PROTOBUF_FIELD_OFFSET(BranchRequest, _impl_.assignment_level_), -1, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedInt32)},
    // int32 decision_level = 7;
    {PROTOBUF_FIELD_OFFSET(BranchRequest, _impl_.decision_level_), _Internal::kHasBitsOffset + 3, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // repeated bool candidate_variable = 8;
    {PROTOBUF_FIELD_OFFSET(BranchRequest, _impl_.candidate_variable_), -1, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedBool)},
    // string model_variant = 9;
    {PROTOBUF_FIELD_OFFSET(BranchRequest, _impl_.model_variant_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .satact_trace.ResponsePayload response_payload = 10;
    {PROTOBUF_FIELD_OFFSET(BranchRequest, _impl_.response_payload_), _Internal::kHasBitsOffset + 4, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
  }},
  // no aux_entries
  {{
    "\32\0\0\0\0\0\0\0\0\15\0\0\0\0\0\0"
    "satact_trace.BranchRequest"
    "model_variant"
  }},
};
PROTOBUF_NOINLINE void BranchRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:satact_trace.BranchRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.c_idxs_.Clear();
  _impl_.l_idxs_.Clear();
  _impl_.assignment_value_.Clear();
  _impl_.assignment_level_.Clear();
  _impl_.candidate_variable_.Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    _impl_.model_variant_.ClearNonDefaultToEmpty();
  }
  if ((cached_has_bits & 0x0000001eu) != 0) {
    ::memset(&_impl_.n_vars_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.response_payload_) -
        reinterpret_cast<char*>(&_impl_.n_vars_)) + sizeof(_impl_.response_payload_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL BranchRequest::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const BranchRequest& this_ = static_cast<const BranchRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL BranchRequest::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const BranchRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:satact_trace.BranchRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 n_vars = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000002u) != 0) {
    if (this_._internal_n_vars() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<1>(
              stream, this_._internal_n_vars(), target);
    }
  }

  // int32 n_clauses = 2;
  if ((this_._impl_._has_bits_[0] & 0x00000004u) != 0) {
    if (this_._internal_n_clauses() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<2>(
              stream, this_._internal_n_clauses(), target);
    }
  }

  // repeated int32 c_idxs = 3;
  {
    int byte_size = this_._impl_._c_idxs_cached_byte_size_.Get();
    if (byte_size > 0) {
      target = stream->WriteInt32Packed(
          3, this_._internal_c_idxs(), byte_size, target);
    }
  }

  // repeated int32 l_idxs = 4;
  {
    int byte_size = this_._impl_._l_idxs_cached_byte_size_.Get();
    if (byte_size > 0) {
      target = stream->WriteInt32Packed(
          4, this_._internal_l_idxs(), byte_size, target);
    }
  }

  // repeated int32 assignment_value = 5;
  {
    int byte_size = this_._impl_._assignment_value_cached_byte_size_.Get();
    if (byte_size > 0) {
      target = stream->WriteInt32Packed(
          5, this_._internal_assignment_value(), byte_size, target);
    }
  }

  // repeated int32 assignment_level = 6;
  {
    int byte_size = this_._impl_._assignment_level_cached_byte_size_.Get();
    if (byte_size > 0) {
      target = stream->WriteInt32Packed(
          6, this_._internal_assignment_level(), byte_size, target);
    }
  }

  // int32 decision_level = 7;
  if ((this_._impl_._has_bits_[0] & 0x00000008u) != 0) {
    if (this_._internal_decision_level() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<7>(
              stream, this_._internal_decision_level(), target);
    }
  }

  // repeated bool candidate_variable = 8;
  if (this_._internal_candidate_variable_size() > 0) {
    target = stream->WriteFixedPacked(8, this_._internal_candidate_variable(), target);
  }

  // string model_variant = 9;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (!this_._internal_model_variant().empty()) {
      const ::std::string& _s = this_._internal_model_variant();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "satact_trace.BranchRequest.model_variant");
      target = stream->WriteStringMaybeAliased(9, _s, target);
    }
  }

  // .satact_trace.ResponsePayload response_payload = 10;
  if ((this_._impl_._has_bits_[0] & 0x00000010u) != 0) {
    if (this_._internal_response_payload() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          10, this_._internal_response_payload(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:satact_trace.BranchRequest)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t BranchRequest::ByteSizeLong(const MessageLite& base) {
  const BranchRequest& this_ = static_cast<const BranchRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t BranchRequest::ByteSizeLong() const {
  const BranchRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:satact_trace.BranchRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
   {
    // repeated int32 c_idxs = 3;
    {
      total_size +=
          ::_pbi::WireFormatLite::Int32SizeWithPackedTagSize(
              this_._internal_c_idxs(), 1,
              this_._impl_._c_idxs_cached_byte_size_);
    }
    // repeated int32 l_idxs = 4;
    {
      total_size +=
          ::_pbi::WireFormatLite::Int32SizeWithPackedTagSize(
              this_._internal_l_idxs(), 1,
              this_._impl_._l_idxs_cached_byte_size_);
    }
    // repeated int32 assignment_value = 5;
    {
      total_size +=
          ::_pbi::WireFormatLite::Int32SizeWithPackedTagSize(
              this_._internal_assignment_value(), 1,
              this_._impl_._assignment_value_cached_byte_size_);
    }
    // repeated int32 assignment_level = 6;
    {
      total_size +=
          ::_pbi::WireFormatLite::Int32SizeWithPackedTagSize(
              this_._internal_assignment_level(), 1,
              this_._impl_._assignment_level_cached_byte_size_);
    }
    // repeated bool candidate_variable = 8;
    {
      ::size_t data_size = ::size_t{1} *
          ::_pbi::FromIntSize(this_._internal_candidate_variable_size());
      ::size_t tag_size = data_size == 0
          ? 0
          : 1 + ::_pbi::WireFormatLite::Int32Size(
                              static_cast<::int32_t>(data_size));
      total_size += tag_size + data_size;
    }
  }
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x0000001fu) != 0) {
    // string model_variant = 9;
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!this_._internal_model_variant().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_model_variant());
      }
    }
    // int32 n_vars = 1;
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (this_._internal_n_vars() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_n_vars());
      }
    }
    // int32 n_clauses = 2;
    if ((cached_has_bits & 0x00000004u) != 0) {
      if (this_._internal_n_clauses() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_n_clauses());
      }
    }
    // int32 decision_level = 7;
    if ((cached_has_bits & 0x00000008u) != 0) {
      if (this_._internal_decision_level() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_decision_level());
      }
    }
    // .satact_trace.ResponsePayload response_payload = 10;
    if ((cached_has_bits & 0x00000010u) != 0) {
      if (this_._internal_response_payload() != 0) {
        total_size += 1 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_response_payload());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void BranchRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<BranchRequest*>(&to_msg);
  auto& from = static_cast<const BranchRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:satact_trace.BranchRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_c_idxs()->MergeFrom(from._internal_c_idxs());
  _this->_internal_mutable_l_idxs()->MergeFrom(from._internal_l_idxs());
  _this->_internal_mutable_assignment_value()->MergeFrom(from._internal_assignment_value());
  _this->_internal_mutable_assignment_level()->MergeFrom(from._internal_assignment_level());
  _this->_internal_mutable_candidate_variable()->MergeFrom(from._internal_candidate_variable());
  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x0000001fu) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!from._internal_model_variant().empty()) {
        _this->_internal_set_model_variant(from._internal_model_variant());
      } else {
        if (_this->_impl_.model_variant_.IsDefault()) {
          _this->_internal_set_model_variant("");
        }
      }
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (from._internal_n_vars() != 0) {
        _this->_impl_.n_vars_ = from._impl_.n_vars_;
      }
    }
    if ((cached_has_bits & 0x00000004u) != 0) {
      if (from._internal_n_clauses() != 0) {
        _this->_impl_.n_clauses_ = from._impl_.n_clauses_;
      }
    }
    if ((cached_has_bits & 0x00000008u) != 0) {
      if (from._internal_decision_level() != 0) {
        _this->_impl_.decision_level_ = from._impl_.decision_level_;
      }
    }
    if ((cached_has_bits & 0x00000010u) != 0) {
      if (from._internal_response_payload() != 0) {
        _this->_impl_.response_payload_ = from._impl_.response_payload_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void BranchRequest::CopyFrom(const BranchRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:satact_trace.BranchRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void BranchRequest::InternalSwap(BranchRequest* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.c_idxs_.InternalSwap(&other->_impl_.c_idxs_);
  _impl_.l_idxs_.InternalSwap(&other->_impl_.l_idxs_);
  _impl_.assignment_value_.InternalSwap(&other->_impl_.assignment_value_);
  _impl_.assignment_level_.InternalSwap(&other->_impl_.assignment_level_);
  _impl_.candidate_variable_.InternalSwap(&other->_impl_.candidate_variable_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.model_variant_, &other->_impl_.model_variant_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(BranchRequest, _impl_.response_payload_)
      + sizeof(BranchRequest::_impl_.response_payload_)
      - PROTOBUF_FIELD_OFFSET(BranchRequest, _impl_.n_vars_)>(
          reinterpret_cast<char*>(&_impl_.n_vars_),
          reinterpret_cast<char*>(&other->_impl_.n_vars_));
}

::google::protobuf::Metadata BranchRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class BranchDecision::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<BranchDecision>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(BranchDecision, _impl_._has_bits_);
};

BranchDecision::BranchDecision(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, BranchDecision_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:satact_trace.BranchDecision)
}
PROTOBUF_NDEBUG_INLINE BranchDecision::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::satact_trace::BranchDecision& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        action_logits_{visibility, arena, from.action_logits_},
        msg_(arena, from.msg_),
        model_variant_(arena, from.model_variant_) {}

BranchDecision::BranchDecision(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const BranchDecision& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, BranchDecision_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  BranchDecision* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, success_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, success_),
           offsetof(Impl_, response_payload_) -
               offsetof(Impl_, success_) +
               sizeof(Impl_::response_payload_));

  // @@protoc_insertion_point(copy_constructor:satact_trace.BranchDecision)
}
PROTOBUF_NDEBUG_INLINE BranchDecision::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        action_logits_{visibility, arena},
        msg_(arena),
        model_variant_(arena) {}

inline void BranchDecision::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, success_),
           0,
           offsetof(Impl_, response_payload_) -
               offsetof(Impl_, success_) +
               sizeof(Impl_::response_payload_));
}
BranchDecision::~BranchDecision() {
  // @@protoc_insertion_point(destructor:satact_trace.BranchDecision)
  SharedDtor(*this);
}
inline void BranchDecision::SharedDtor(MessageLite& self) {
  BranchDecision& this_ = static_cast<BranchDecision&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.msg_.Destroy();
  this_._impl_.model_variant_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL BranchDecision::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) BranchDecision(arena);
}
constexpr auto BranchDecision::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(BranchDecision, _impl_.action_logits_) +
          decltype(BranchDecision::_impl_.action_logits_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(BranchDecision), alignof(BranchDecision), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&BranchDecision::PlacementNew_,
                                 sizeof(BranchDecision),
                                 alignof(BranchDecision));
  }
}
constexpr auto BranchDecision::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_BranchDecision_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &BranchDecision::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<BranchDecision>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &BranchDecision::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<BranchDecision>(), &BranchDecision::ByteSizeLong,
              &BranchDecision::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(BranchDecision, _impl_._cached_size_),
          false,
      },
      &BranchDecision::kDescriptorMethods,
      &descriptor_table_satact_5ftrace_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull BranchDecision_class_data_ =
        BranchDecision::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
BranchDecision::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&BranchDecision_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(BranchDecision_class_data_.tc_table);
  return BranchDecision_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<4, 9, 0, 60, 2>
BranchDecision::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(BranchDecision, _impl_._has_bits_),
    0, // no _extensions_
    9, 120,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294966784,  // skipmap
    offsetof(decltype(_table_), field_entries),
    9,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    BranchDecision_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::satact_trace::BranchDecision>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // bool success = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(BranchDecision, _impl_.success_), 2>(),
     {8, 2, 0, PROTOBUF_FIELD_OFFSET(BranchDecision, _impl_.success_)}},
    // string msg = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 0, 0, PROTOBUF_FIELD_OFFSET(BranchDecision, _impl_.msg_)}},
    // float n_secs_inference = 3;
    {::_pbi::TcParser::FastF32S1,
     {29, 3, 0, PROTOBUF_FIELD_OFFSET(BranchDecision, _impl_.n_secs_inference_)}},
    // string model_variant = 4;
    {::_pbi::TcParser::FastUS1,
     {34, 1, 0, PROTOBUF_FIELD_OFFSET(BranchDecision, _impl_.model_variant_)}},
    // .satact_trace.Action action = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(BranchDecision, _impl_.action_), 4>(),
     {40, 4, 0, PROTOBUF_FIELD_OFFSET(BranchDecision, _impl_.action_)}},
    // int32 selected_literal_index = 6;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(BranchDecision, _impl_.selected_literal_index_), 5>(),
     {48, 5, 0, PROTOBUF_FIELD_OFFSET(BranchDecision, _impl_.selected_literal_index_)}},
    // float selected_log_probability = 7;
    {::_pbi::TcParser::FastF32S1,
     {61, 6, 0, PROTOBUF_FIELD_OFFSET(BranchDecision, _impl_.selected_log_probability_)}},
    // .satact_trace.ResponsePayload response_payload = 8;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(BranchDecision, _impl_.response_payload_), 7>(),
     {64, 7, 0, PROTOBUF_FIELD_OFFSET(BranchDecision, _impl_.response_payload_)}},
    // repeated float action_logits = 9;
    {::_pbi::TcParser::FastF32P1,
     {74, 63, 0, PROTOBUF_FIELD_OFFSET(BranchDecision, _impl_.action_logits_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // bool success = 1;
    {PROTOBUF_FIELD_OFFSET(BranchDecision, _impl_.success_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // string msg = 2;
    {PROTOBUF_FIELD_OFFSET(BranchDecision, _impl_.msg_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // float n_secs_inference = 3;
    {PROTOBUF_FIELD_OFFSET(BranchDecision, _impl_.n_secs_inference_), _Internal::kHasBitsOffset + 3, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // string model_variant = 4;
    {PROTOBUF_FIELD_OFFSET(BranchDecision, _impl_.model_variant_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .satact_trace.Action action = 5;
    {PROTOBUF_FIELD_OFFSET(BranchDecision, _impl_.action_), _Internal::kHasBitsOffset + 4, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
    // int32 selected_literal_index = 6;
    {PROTOBUF_FIELD_OFFSET(BranchDecision, _impl_.selected_literal_index_), _Internal::kHasBitsOffset + 5, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // float selected_log_probability = 7;
    {PROTOBUF_FIELD_OFFSET(BranchDecision, _impl_.selected_log_probability_), _Internal::kHasBitsOffset + 6, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // .satact_trace.ResponsePayload response_payload = 8;
    {PROTOBUF_FIELD_OFFSET(BranchDecision, _impl_.response_payload_), _Internal::kHasBitsOffset + 7, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
    // repeated float action_logits = 9;
    {PROTOBUF_FIELD_OFFSET(BranchDecision, _impl_.action_logits_), -1, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedFloat)},
  }},
  // no aux_entries
  {{
    "\33\0\3\0\15\0\0\0\0\0\0\0\0\0\0\0"
    "satact_trace.BranchDecision"
    "msg"
    "model_variant"
  }},
};
PROTOBUF_NOINLINE void BranchDecision::Clear() {
// @@protoc_insertion_point(message_clear_start:satact_trace.BranchDecision)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.action_logits_.Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      _impl_.msg_.ClearNonDefaultToEmpty();
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      _impl_.model_variant_.ClearNonDefaultToEmpty();
    }
  }
  if ((cached_has_bits & 0x000000fcu) != 0) {
    ::memset(&_impl_.success_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.response_payload_) -
        reinterpret_cast<char*>(&_impl_.success_)) + sizeof(_impl_.response_payload_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL BranchDecision::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const BranchDecision& this_ = static_cast<const BranchDecision&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL BranchDecision::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const BranchDecision& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:satact_trace.BranchDecision)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // bool success = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000004u) != 0) {
    if (this_._internal_success() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteBoolToArray(
          1, this_._internal_success(), target);
    }
  }

  // string msg = 2;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (!this_._internal_msg().empty()) {
      const ::std::string& _s = this_._internal_msg();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "satact_trace.BranchDecision.msg");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  // float n_secs_inference = 3;
  if ((this_._impl_._has_bits_[0] & 0x00000008u) != 0) {
    if (::absl::bit_cast<::uint32_t>(this_._internal_n_secs_inference()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteFloatToArray(
          3, this_._internal_n_secs_inference(), target);
    }
  }

  // string model_variant = 4;
  if ((this_._impl_._has_bits_[0] & 0x00000002u) != 0) {
    if (!this_._internal_model_variant().empty()) {
      const ::std::string& _s = this_._internal_model_variant();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "satact_trace.BranchDecision.model_variant");
      target = stream->WriteStringMaybeAliased(4, _s, target);
    }
  }

  // .satact_trace.Action action = 5;
  if ((this_._impl_._has_bits_[0] & 0x00000010u) != 0) {
    if (this_._internal_action() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          5, this_._internal_action(), target);
    }
  }

  // int32 selected_literal_index = 6;
  if ((this_._impl_._has_bits_[0] & 0x00000020u) != 0) {
    if (this_._internal_selected_literal_index() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<6>(
              stream, this_._internal_selected_literal_index(), target);
    }
  }

  // float selected_log_probability = 7;
  if ((this_._impl_._has_bits_[0] & 0x00000040u) != 0) {
    if (::absl::bit_cast<::uint32_t>(this_._internal_selected_log_probability()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteFloatToArray(
          7, this_._internal_selected_log_probability(), target);
    }
  }

  // .satact_trace.ResponsePayload response_payload = 8;
  if ((this_._impl_._has_bits_[0] & 0x00000080u) != 0) {
    if (this_._internal_response_payload() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          8, this_._internal_response_payload(), target);
    }
  }

  // repeated float action_logits = 9;
  if (this_._internal_action_logits_size() > 0) {
    target = stream->WriteFixedPacked(9, this_._internal_action_logits(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:satact_trace.BranchDecision)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t BranchDecision::ByteSizeLong(const MessageLite& base) {
  const BranchDecision& this_ = static_cast<const BranchDecision&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t BranchDecision::ByteSizeLong() const {
  const BranchDecision& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:satact_trace.BranchDecision)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
   {
    // repeated float action_logits = 9;
    {
      ::size_t data_size = ::size_t{4} *
          ::_pbi::FromIntSize(this_._internal_action_logits_size());
      ::size_t tag_size = data_size == 0
          ? 0
          : 1 + ::_pbi::WireFormatLite::Int32Size(
                              static_cast<::int32_t>(data_size));
      total_size += tag_size + data_size;
    }
  }
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x000000ffu) != 0) {
    // string msg = 2;
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!this_._internal_msg().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_msg());
      }
    }
    // string model_variant = 4;
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (!this_._internal_model_variant().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_model_variant());
      }
    }
    // bool success = 1;
    if ((cached_has_bits & 0x00000004u) != 0) {
      if (this_._internal_success() != 0) {
        total_size += 2;
      }
    }
    // float n_secs_inference = 3;
    if ((cached_has_bits & 0x00000008u) != 0) {
      if (::absl::bit_cast<::uint32_t>(this_._internal_n_secs_inference()) != 0) {
        total_size += 5;
      }
    }
    // .satact_trace.Action action = 5;
    if ((cached_has_bits & 0x00000010u) != 0) {
      if (this_._internal_action() != 0) {
        total_size += 1 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_action());
      }
    }
    // int32 selected_literal_index = 6;
    if ((cached_has_bits & 0x00000020u) != 0) {
      if (this_._internal_selected_literal_index() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_selected_literal_index());
      }
    }
    // float selected_log_probability = 7;
    if ((cached_has_bits & 0x00000040u) != 0) {
      if (::absl::bit_cast<::uint32_t>(this_._internal_selected_log_probability()) != 0) {
        total_size += 5;
      }
    }
    // .satact_trace.ResponsePayload response_payload = 8;
    if ((cached_has_bits & 0x00000080u) != 0) {
      if (this_._internal_response_payload() != 0) {
        total_size += 1 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_response_payload());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void BranchDecision::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<BranchDecision*>(&to_msg);
  auto& from = static_cast<const BranchDecision&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:satact_trace.BranchDecision)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_action_logits()->MergeFrom(from._internal_action_logits());
  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x000000ffu) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!from._internal_msg().empty()) {
        _this->_internal_set_msg(from._internal_msg());
      } else {
        if (_this->_impl_.msg_.IsDefault()) {
          _this->_internal_set_msg("");
        }
      }
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (!from._internal_model_variant().empty()) {
        _this->_internal_set_model_variant(from._internal_model_variant());
      } else {
        if (_this->_impl_.model_variant_.IsDefault()) {
          _this->_internal_set_model_variant("");
        }
      }
    }
    if ((cached_has_bits & 0x00000004u) != 0) {
      if (from._internal_success() != 0) {
        _this->_impl_.success_ = from._impl_.success_;
      }
    }
    if ((cached_has_bits & 0x00000008u) != 0) {
      if (::absl::bit_cast<::uint32_t>(from._internal_n_secs_inference()) != 0) {
        _this->_impl_.n_secs_inference_ = from._impl_.n_secs_inference_;
      }
    }
    if ((cached_has_bits & 0x00000010u) != 0) {
      if (from._internal_action() != 0) {
        _this->_impl_.action_ = from._impl_.action_;
      }
    }
    if ((cached_has_bits & 0x00000020u) != 0) {
      if (from._internal_selected_literal_index() != 0) {
        _this->_impl_.selected_literal_index_ = from._impl_.selected_literal_index_;
      }
    }
    if ((cached_has_bits & 0x00000040u) != 0) {
      if (::absl::bit_cast<::uint32_t>(from._internal_selected_log_probability()) != 0) {
        _this->_impl_.selected_log_probability_ = from._impl_.selected_log_probability_;
      }
    }
    if ((cached_has_bits & 0x00000080u) != 0) {
      if (from._internal_response_payload() != 0) {
        _this->_impl_.response_payload_ = from._impl_.response_payload_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void BranchDecision::CopyFrom(const BranchDecision& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:satact_trace.BranchDecision)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void BranchDecision::InternalSwap(BranchDecision* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.action_logits_.InternalSwap(&other->_impl_.action_logits_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.msg_, &other->_impl_.msg_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.model_variant_, &other->_impl_.model_variant_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(BranchDecision, _impl_.response_payload_)
      + sizeof(BranchDecision::_impl_.response_payload_)
      - PROTOBUF_FIELD_OFFSET(BranchDecision, _impl_.success_)>(
          reinterpret_cast<char*>(&_impl_.success_),
          reinterpret_cast<char*>(&other->_impl_.success_));
}

::google::protobuf::Metadata BranchDecision::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace satact_trace
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_satact_5ftrace_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
